version: "3.8"
services:

  auditor:
    build:
      context: ./image-auditor
      dockerfile: Dockerfile
    container_name: dai-auditor

  musician:
    build:
      context: ./image-musician
      dockerfile: Dockerfile
    container_name: dai-musician

#docker-compose up  --force-recreate -d
#docker-compose down
